name: "[ PRD ] Build and Upload to Azure Blob Storage"

# 모든 환경 변수는 Github의 variables 및 secrets 에서 관리 합니다.

env:
  # JAVA 버전 (ex: 17)
  JAVA_VERSION: "${{ vars.JAVA_VERSION }}"

  # AZURE Storage Account 이름 (ex : ccoetmpblob)
  AZURE_STORAGE_ACCOUNT: "${{ vars.AZURE_STORAGE_ACCOUNT }}"

  # AZURE Storage Access Key (secrets)
  AZURE_STORAGE_ACCESS_KEY: "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"

  # AZURE Container 이름 (ex : ccoetmpblobcnt DEV | PRD)
  # Container 이름으로 dev 와 prd 구분
  AZURE_CONTAINER_NAME: "${{ vars.AZURE_CONTAINER_NAME_PRD }}"

  # Application 이름 (ex: jar로 생성될 파일 이름 abc.jar)
  APP_NAME: "${{ vars.APP_NAME }}"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
        type: choice
        options:
          - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Print Environment Variables
        run: |
          echo "Workflow Actor = ${{ github.actor }}"
          echo "JAVA_VERSION = ${{ env.JAVA_VERSION }}"
          echo "AZURE_STORAGE_ACCOUNT = ${{ env.AZURE_STORAGE_ACCOUNT }}"
          echo "AZURE_CONTAINER_NAME = ${{ env.AZURE_CONTAINER_NAME }}"
          echo "APP_NAME = ${{ env.APP_NAME }}"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Check target directory
        run: |
          echo "Listing target directory contents:"
          ls -la target/

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "Starting upload to Azure Blob Storage..."
            az storage blob upload \
              --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
              --container-name ${{ env.AZURE_CONTAINER_NAME }} \
              --name ${{ env.APP_NAME }}.jar \
              --file target/${{ env.APP_NAME }}.jar \
              --overwrite \
              --account-key ${{ env.AZURE_STORAGE_ACCESS_KEY }}
            echo "Upload completed successfully"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}.jar
          path: target/${{ env.APP_NAME }}.jar